### ISSUE TITLE
Error in alpine::fitBiasModels shows as "offset needs to be finite"

### ISSUE THREAD

**Issue by nagzz** [mikelove/alpine#7]
Hi
While implementing the fitbiasmodel, I end up with the following error. Could you please check and let me know the possible solution to resolve the error.

```
> Error in alpine::fitBiasModels(genes = ebtFit, bam.file = bf, fragtypes = fragtypes,  : 
>   offset needs to be finite
```
Thanks,
Nagesh

**Comment by mikelove** [comment]
Can you post to the support site and provide a lot more details? Eg all your code
