### ISSUE TITLE
how to use the learned model to correct for RNA-seq coverage

### ISSUE THREAD

**Issue by haibol2016** [mikelove/alpine#8]
@mikelove 

        In the Vignette, you showed that the learned model can be used to predict RNA-seq read coverage for single-isoform genes. Do you have a guide how to use the learned model to correct for RNA-seq coverage for any genes?

Thanks

**Comment by mikelove** [comment]
For multi-isoform genes you just need to multiply the predicted coverage by the estimate of `theta` the abundance.

I'm not sure if it would be easy to code this up.

However, there is a new software package that leverages alpine which implements this prediction for multi-isoform genes:

https://www.life-science-alliance.org/content/2/1/e201800175.abstract

https://github.com/csoneson/jcc

**Comment by haibol2016** [comment]
@mikelove 

Hello Mike,
   Thank you for you quick response. 
   Based on my understanding, the predict coverage is a theoretical coverage give the transcript's structure, GC%, GC stretches, and read relative position at 5' end and 3' end. What I want to have is an inferred coverage after adjusting for the biases (positional, GC%, GC stretch, fragment length, ...), which should be less noisy (jumpy) than the observed coverage from RNA-seq data. For example, in DNA-seq, GC% is used to adjust the bias caused by local GC-content to make the coverage more evenly, which will facilitate DNA copy number variant calling. 
    For  RNA-seq data, I am not sure how the learned model can be used to adjust biases to get smoothed coverage. So I think JCC package is not a good choice for me.
    Best,

Haibo

**Comment by mikelove** [comment]
JCC is about comparing the observed coverage to expected given the model. 

It sounds like you want the residual coverage after removing the bias (this is what JCC does internally basically). I think you should be able to do this with your own R code but we don't have anything implemented.
