### ISSUE TITLE
S4Vectors `fancy_mseq()` removed as of version 0.29.2

### ISSUE THREAD

**Issue by isaacvock** [mikelove/alpine#9]
Hello @mikelove,

An unexported function in alpine, `mapTx2Gene`, calls `S4Vectors:::fancy_mseq` which was removed a couple years ago (see [this commit](https://github.com/Bioconductor/S4Vectors/commit/07a75c72b6654d510f52d31ad0975fc24a67fa91)). This breaks standard usage of the jcc package. I am happy to make a pull request with the following replacement that I found to replicate fancy_mseq's behavior:

```
mapTxToGenome <- function(exons) {
  strand <- as.character(strand(exons)[1])
  stopifnot(all(exons$exon_rank == seq_along(exons)))
  
  ### Hack to replicate `rev` from old S4Vectors:::fancy_mseq
  froms <- ifelse(strand == "-",
                  start(exons) + width(exons) - 1L,
                  start(exons))
  bys <- 1L*ifelse(strand == "-", -1L, 1L)
  
  bases <- sequence(width(exons), from = froms,
                    by = bys)

  data.frame(tx=seq_along(bases),
             genome=bases,
             exon_rank=rep(exons$exon_rank, width(exons)))
}
```

Let me know your thoughts,
Isaac

**Comment by mikelove** [comment]
Sure! Alpine is now off of Bioconductor, but I'm happy to take PRs here if they help it to continue to work with other packages.
